// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ActionSecretHandlerFunction
 */
export interface ActionSecretHandlerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/handler/secrets/action-secrets/action-secret-handler.
 */
export class ActionSecretHandlerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ActionSecretHandlerFunctionProps) {
    super(scope, id, {
      description: 'src/handler/secrets/action-secrets/action-secret-handler.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/handler/secrets/action-secrets/action-secret-handler.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}