// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for GithubResourceHandlerFunction
 */
export interface GithubResourceHandlerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/handler/github-resource/github-resource-handler.
 */
export class GithubResourceHandlerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: GithubResourceHandlerFunctionProps) {
    super(scope, id, {
      description: 'src/handler/github-resource/github-resource-handler.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/handler/github-resource/github-resource-handler.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}